# Generated by Django 5.1.7 on 2025-03-23 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('full_videos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='path',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
