# Generated by Django 5.1.7 on 2025-03-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('full_videos', '0002_video_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='video',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='photos/'),
        ),
    ]
